[2025-02-14T18:07:52.947+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T18:07:52.976+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.test_aws_connection manual__2025-02-14T18:07:47.799654+00:00 [queued]>
[2025-02-14T18:07:52.982+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.test_aws_connection manual__2025-02-14T18:07:47.799654+00:00 [queued]>
[2025-02-14T18:07:52.983+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-14T18:07:52.994+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_aws_connection> on 2025-02-14 18:07:47.799654+00:00
[2025-02-14T18:07:53.014+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3078) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T18:07:53.020+0000] {standard_task_runner.py:72} INFO - Started process 3079 to run task
[2025-02-14T18:07:53.019+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'test_aws_connection', 'manual__2025-02-14T18:07:47.799654+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmp9kvcfllx']
[2025-02-14T18:07:53.030+0000] {standard_task_runner.py:105} INFO - Job 216: Subtask test_aws_connection
[2025-02-14T18:07:53.084+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.test_aws_connection manual__2025-02-14T18:07:47.799654+00:00 [running]> on host 715f5b9093d1
[2025-02-14T18:07:53.161+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='test_aws_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T18:07:47.799654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T18:07:47.799654+00:00'
[2025-02-14T18:07:53.163+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T18:07:53.187+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-14T18:07:53.188+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-02-14T18:07:54.970+0000] {logging_mixin.py:190} INFO - Connection successful!
[2025-02-14T18:07:54.973+0000] {logging_mixin.py:190} INFO - Objects found: ['importFiles/2009q1/num.txt', 'importFiles/2009q1/pre.txt', 'importFiles/2009q1/readme.htm', 'importFiles/2009q1/sub.txt', 'importFiles/2009q1/tag.txt']
[2025-02-14T18:07:54.983+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T18:07:55.027+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T18:07:55.028+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=test_aws_connection, run_id=manual__2025-02-14T18:07:47.799654+00:00, execution_date=20250214T180747, start_date=20250214T180752, end_date=20250214T180755
[2025-02-14T18:07:55.113+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T18:07:55.198+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-14T18:07:55.200+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
