[2025-02-14T17:52:46.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T17:52:46.438+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.process_one_file manual__2025-02-14T17:50:25.851942+00:00 [queued]>
[2025-02-14T17:52:46.444+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.process_one_file manual__2025-02-14T17:50:25.851942+00:00 [queued]>
[2025-02-14T17:52:46.444+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-14T17:52:46.455+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_one_file> on 2025-02-14 17:50:25.851942+00:00
[2025-02-14T17:52:46.495+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'process_one_file', 'manual__2025-02-14T17:50:25.851942+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmptwhadmsi']
[2025-02-14T17:52:46.503+0000] {standard_task_runner.py:105} INFO - Job 212: Subtask process_one_file
[2025-02-14T17:52:46.494+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2897) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T17:52:46.504+0000] {standard_task_runner.py:72} INFO - Started process 2898 to run task
[2025-02-14T17:52:46.566+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.process_one_file manual__2025-02-14T17:50:25.851942+00:00 [running]> on host 715f5b9093d1
[2025-02-14T17:52:46.627+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='process_one_file' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T17:50:25.851942+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T17:50:25.851942+00:00'
[2025-02-14T17:52:46.628+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T17:52:46.641+0000] {transform_sec_data.py:26} INFO - Processing sub.txt from 2016q4...
[2025-02-14T17:52:46.649+0000] {base.py:84} INFO - Retrieving connection 'aws_default'
[2025-02-14T17:52:46.649+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-02-14T17:52:48.021+0000] {warnings.py:112} WARNING - /opt/***/dags/transform_sec_data.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["period"] = pd.to_datetime(df["period"], errors="coerce").dt.strftime("%Y-%m-%d")

[2025-02-14T17:52:51.044+0000] {transform_sec_data.py:51} INFO - âœ… Transformed and uploaded: sec-transformed-files/2016q4/sub.csv
[2025-02-14T17:52:51.053+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T17:52:51.313+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T17:52:51.315+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=process_one_file, run_id=manual__2025-02-14T17:50:25.851942+00:00, execution_date=20250214T175025, start_date=20250214T175246, end_date=20250214T175251
[2025-02-14T17:52:51.448+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T17:52:51.516+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-02-14T17:52:51.620+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T17:52:51.624+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
