[2025-02-14T16:37:33.432+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T16:37:33.445+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.create_snowflake_table manual__2025-02-14T16:35:17.596830+00:00 [queued]>
[2025-02-14T16:37:33.451+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.create_snowflake_table manual__2025-02-14T16:35:17.596830+00:00 [queued]>
[2025-02-14T16:37:33.451+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-14T16:37:33.461+0000] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): create_snowflake_table> on 2025-02-14 16:35:17.596830+00:00
[2025-02-14T16:37:33.473+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2003) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T16:37:33.476+0000] {standard_task_runner.py:72} INFO - Started process 2004 to run task
[2025-02-14T16:37:33.475+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'create_snowflake_table', 'manual__2025-02-14T16:35:17.596830+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmppsl7dmih']
[2025-02-14T16:37:33.480+0000] {standard_task_runner.py:105} INFO - Job 195: Subtask create_snowflake_table
[2025-02-14T16:37:33.553+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.create_snowflake_table manual__2025-02-14T16:35:17.596830+00:00 [running]> on host 715f5b9093d1
[2025-02-14T16:37:33.613+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='create_snowflake_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T16:35:17.596830+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T16:35:17.596830+00:00'
[2025-02-14T16:37:33.615+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T16:37:33.636+0000] {sql.py:278} INFO - Executing: 
    CREATE OR REPLACE TABLE sec_2016q4 (
        city string,
        country string,
        data variant,
        enddate date,
        name string,
        secquarter string,
        startdate date,
        symbol string,
        secyear int
    );
    
[2025-02-14T16:37:33.650+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T16:37:33.660+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-14T16:37:33.661+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-02-14T16:37:33.662+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-02-14T16:37:33.663+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-14T16:37:34.432+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T16:37:34.433+0000] {sql.py:553} INFO - Running statement: CREATE OR REPLACE TABLE sec_2016q4 (
        city string,
        country string,
        data variant,
        enddate date,
        name string,
        secquarter string,
        startdate date,
        symbol string,
        secyear int
    );, parameters: None
[2025-02-14T16:37:34.754+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T16:37:34.756+0000] {sql.py:562} INFO - Rows affected: 1
[2025-02-14T16:37:34.758+0000] {snowflake.py:447} INFO - Rows affected: 1
[2025-02-14T16:37:34.758+0000] {snowflake.py:448} INFO - Snowflake query id: 01ba6405-3202-c686-0005-f9060003402a
[2025-02-14T16:37:34.929+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-14T16:37:34.930+0000] {connection.py:789} INFO - closed
[2025-02-14T16:37:34.991+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-02-14T16:37:35.082+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T16:37:35.083+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=create_snowflake_table, run_id=manual__2025-02-14T16:35:17.596830+00:00, execution_date=20250214T163517, start_date=20250214T163733, end_date=20250214T163735
[2025-02-14T16:37:35.110+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T16:37:35.165+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-14T16:37:35.167+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
